name: Local Environment
values:
  - key: baseUrl
    value: 'http://127.0.0.1:8080'
  - key: moviesServiceUrl
    value: 'http://127.0.0.1:8081'
  - key: eventsServiceUrl
    value: 'http://127.0.0.1:8082'
  - key: proxyServiceUrl
    value: 'http://127.0.0.1:8000'
