apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyAJImF1dGhzIjogeyAJCSJnaGNyLmlvIjogeyAJCQkiYXV0aCI6IlNWTmhiV0oxY25OcmFYazZaMmh3WDNCUlRXSlJTMk4zTjI4d1NGWXhSbk5EVTI1RVNHbzBTV3RsTUdjNVZqRkpPVlJZWVE9PSIgCQl9IAl9LCAJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsIAkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsIAkicGx1Z2lucyI6IHsgCQkiLXgtY2xpLWhpbnRzIjogeyAJCQkiZW5hYmxlZCI6ICJ0cnVlIiAJCX0sIAkJImFpIjogeyAJCQkiaG9va3MiOiAiYnVpbGQsYnVpbGR4IGJ1aWxkLHJ1bixjb21wb3NlIiAJCX0sIAkJImRlYnVnIjogeyAJCQkiaG9va3MiOiAiZXhlYyIgCQl9LCAJCSJzY291dCI6IHsgCQkJImhvb2tzIjogInB1bGwsYnVpbGR4IGJ1aWxkIiAJCX0gCX0sIAkiZmVhdHVyZXMiOiB7IAkJImhvb2tzIjogInRydWUiIAl9IH0=
type: kubernetes.io/dockerconfigjson
